[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = -v
markers =
    smoke: smoke tests
    regression: regression tests
    appointment: appointment related tests
    login: login related tests